name = "heal-spur-2025"
main = "src/index.ts"
account_id = "15da5ad5182674e2b35e8602629bbff9"
routes = [{ pattern = "healens.co/api/*", zone_name = "healens.co" }]
REACT_APP_API_ORIGIN = "https://worker.anthonyhana04.workers.dev"
pages_build_output_dir = "./website/build"